[workspace]

members = [
  "glean-core",
  "glean-core/ffi",
  "glean-core/preview",
  "glean-core/benchmark",
  "glean-core/nimbus-experiments",
]

[profile.release]
opt-level = "s"
debug = false
lto = true
